# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Labelling b 
#' 
#' @name labelling_b_C
#' 
#' @param w w
#' @param phi phi
#' @param f0i f0i
#' @param f1i f1i
labelling_b_C <- function(w, phi, f0i, f1i) {
    .Call('_CoMiRe_labelling_b_C', PACKAGE = 'CoMiRe', w, phi, f0i, f1i)
}

#' @title Labelling bb
#' 
#' @name labelling_bb_C
#' 
#' @param w w
#' @param phi phi
#' @param P0 P0
#' @param P1 P1
labelling_bb_C <- function(w, phi, P0, P1) {
    .Call('_CoMiRe_labelling_bb_C', PACKAGE = 'CoMiRe', w, phi, P0, P1)
}

#' @title Labelling c
#' 
#' @name labelling_c_C
#' 
#' @param y y
#' @param logpi logpi
#' @param mu mu
#' @param tau tau
labelling_c_C <- function(y, logpi, mu, tau) {
    .Call('_CoMiRe_labelling_c_C', PACKAGE = 'CoMiRe', y, logpi, mu, tau)
}

#' @title Mixdensity
#' 
#' @name mixdensity_C
#' 
#' @param y y
#' @param pi pi
#' @param mu mu
#' @param tau tau
mixdensity_C <- function(y, pi, mu, tau) {
    .Call('_CoMiRe_mixdensity_C', PACKAGE = 'CoMiRe', y, pi, mu, tau)
}

#' @title Sample
#' 
#' @name sample
#' 
#' @param vals vals
#' @param probs probs
NULL

